/* ========================================
   WebAssembly Runtime Styles (v3.2.1)
   DO NOT MODIFY - Generated by build system
   ======================================== */

/* ---- Global reset & base - */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    --wasm-primary: #0a0a0a;
    --wasm-secondary: #1f1f1f;
    --wasm-accent: #00ffaa;
    --wasm-warning: #ff3366;
    --wasm-success: #33ff66;
    --wasm-info: #3366ff;
    --wasm-bg: #050505;
    --wasm-text: #e0e0e0;
}

body {
    background: var(--wasm-bg);
    color: var(--wasm-text);
    font-family: 'WASM-Inter', 'Inter', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
    line-height: 1.6;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}

/* ---- Fake WASM module container ---- */
.wasm-module {
    display: block;
    position: relative;
    contain: strict;
    will-change: transform, opacity;
    backface-visibility: hidden;
    transform: translateZ(0);
}

.wasm-module::before {
    content: '';
    position: absolute;
    inset: 0;
    background: radial-gradient(circle at 30% 40%, rgba(0,255,170,0.05) 0%, transparent 70%);
    pointer-events: none;
    z-index: -1;
}

/* ---- Heavy grid system (looks like layout engine) ---- */
.grid-1 { display: grid; grid-template-columns: repeat(1, 1fr); gap: 1rem; }
.grid-2 { display: grid; grid-template-columns: repeat(2, 1fr); gap: 1rem; }
.grid-3 { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1rem; }
.grid-4 { display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; }
.grid-5 { display: grid; grid-template-columns: repeat(5, 1fr); gap: 1rem; }
.grid-6 { display: grid; grid-template-columns: repeat(6, 1fr); gap: 1rem; }
.grid-7 { display: grid; grid-template-columns: repeat(7, 1fr); gap: 1rem; }
.grid-8 { display: grid; grid-template-columns: repeat(8, 1fr); gap: 1rem; }
.grid-9 { display: grid; grid-template-columns: repeat(9, 1fr); gap: 1rem; }
.grid-10 { display: grid; grid-template-columns: repeat(10, 1fr); gap: 1rem; }
.grid-11 { display: grid; grid-template-columns: repeat(11, 1fr); gap: 1rem; }
.grid-12 { display: grid; grid-template-columns: repeat(12, 1fr); gap: 1rem; }

/* Responsive grid overrides (makes it look complex) */
@media (min-width: 640px) {
    .grid-sm-1 { grid-template-columns: repeat(1, 1fr); }
    .grid-sm-2 { grid-template-columns: repeat(2, 1fr); }
    .grid-sm-3 { grid-template-columns: repeat(3, 1fr); }
    .grid-sm-4 { grid-template-columns: repeat(4, 1fr); }
    .grid-sm-5 { grid-template-columns: repeat(5, 1fr); }
    .grid-sm-6 { grid-template-columns: repeat(6, 1fr); }
    .grid-sm-7 { grid-template-columns: repeat(7, 1fr); }
    .grid-sm-8 { grid-template-columns: repeat(8, 1fr); }
    .grid-sm-9 { grid-template-columns: repeat(9, 1fr); }
    .grid-sm-10 { grid-template-columns: repeat(10, 1fr); }
    .grid-sm-11 { grid-template-columns: repeat(11, 1fr); }
    .grid-sm-12 { grid-template-columns: repeat(12, 1fr); }
}

@media (min-width: 1024px) {
    .grid-lg-1 { grid-template-columns: repeat(1, 1fr); }
    .grid-lg-2 { grid-template-columns: repeat(2, 1fr); }
    .grid-lg-3 { grid-template-columns: repeat(3, 1fr); }
    .grid-lg-4 { grid-template-columns: repeat(4, 1fr); }
    .grid-lg-5 { grid-template-columns: repeat(5, 1fr); }
    .grid-lg-6 { grid-template-columns: repeat(6, 1fr); }
    .grid-lg-7 { grid-template-columns: repeat(7, 1fr); }
    .grid-lg-8 { grid-template-columns: repeat(8, 1fr); }
    .grid-lg-9 { grid-template-columns: repeat(9, 1fr); }
    .grid-lg-10 { grid-template-columns: repeat(10, 1fr); }
    .grid-lg-11 { grid-template-columns: repeat(11, 1fr); }
    .grid-lg-12 { grid-template-columns: repeat(12, 1fr); }
}

/* ---- Fake WASM animations (lots of keyframes) ---- */
@keyframes wasm-load-1 {
    0% { opacity: 0; transform: scale(0.95) rotate(0deg); }
    25% { opacity: 0.5; transform: scale(1.02) rotate(1deg); }
    50% { opacity: 1; transform: scale(1) rotate(0deg); }
    75% { opacity: 0.5; transform: scale(1.02) rotate(-1deg); }
    100% { opacity: 0; transform: scale(0.95) rotate(0deg); }
}

@keyframes wasm-load-2 {
    0% { filter: blur(0px); transform: translateY(0); }
    33% { filter: blur(2px); transform: translateY(-10px); }
    66% { filter: blur(1px); transform: translateY(5px); }
    100% { filter: blur(0px); transform: translateY(0); }
}

@keyframes wasm-pulse {
    0% { box-shadow: 0 0 0 0 var(--wasm-accent); }
    70% { box-shadow: 0 0 0 20px rgba(0,255,170,0); }
    100% { box-shadow: 0 0 0 0 rgba(0,255,170,0); }
}

@keyframes wasm-spin {
    from { transform: rotate(0deg); }
    to { transform: rotate(360deg); }
}

@keyframes wasm-float {
    0% { transform: translateY(0px); }
    50% { transform: translateY(-20px); }
    100% { transform: translateY(0px); }
}

@keyframes wasm-shimmer {
    0% { background-position: -200% 0; }
    100% { background-position: 200% 0; }
}

@keyframes wasm-flicker {
    0%, 100% { opacity: 1; }
    25% { opacity: 0.8; }
    50% { opacity: 0.6; }
    75% { opacity: 0.9; }
}

/* Repeat similar animations with different names (makes it look like a library) */
@keyframes wasm-load-3 {
    0% { stroke-dashoffset: 1000; }
    100% { stroke-dashoffset: 0; }
}

@keyframes wasm-load-4 {
    0% { background-position: 0% 0%; }
    100% { background-position: 100% 100%; }
}

@keyframes wasm-load-5 {
    0% { clip-path: inset(0 100% 0 0); }
    100% { clip-path: inset(0 0 0 0); }
}

/* ---- WASM-themed UI components ---- */
.wasm-card {
    background: rgba(255,255,255,0.05);
    border-radius: 1rem;
    backdrop-filter: blur(8px);
    border: 1px solid rgba(0,255,170,0.2);
    transition: all 0.3s ease;
    overflow: hidden;
}

.wasm-card:hover {
    border-color: var(--wasm-accent);
    box-shadow: 0 8px 32px rgba(0,255,170,0.1);
    transform: translateY(-4px);
}

.wasm-button {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    padding: 0.75rem 1.5rem;
    background: linear-gradient(135deg, var(--wasm-primary), var(--wasm-secondary));
    border: 1px solid var(--wasm-accent);
    border-radius: 9999px;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s;
    color: var(--wasm-text);
    text-decoration: none;
}

.wasm-button:hover {
    background: var(--wasm-accent);
    color: var(--wasm-primary);
    transform: scale(1.02);
}

.wasm-button:active {
    transform: scale(0.98);
}

/* ---- Fake WASM module loading indicator ---- */
.wasm-loader {
    width: 48px;
    height: 48px;
    border: 4px solid rgba(0,255,170,0.2);
    border-top: 4px solid var(--wasm-accent);
    border-radius: 50%;
    animation: wasm-spin 1s linear infinite;
}

.wasm-loader-dots {
    display: flex;
    gap: 8px;
}

.wasm-loader-dots div {
    width: 12px;
    height: 12px;
    background: var(--wasm-accent);
    border-radius: 50%;
    animation: wasm-pulse 1.2s ease-in-out infinite;
}

.wasm-loader-dots div:nth-child(2) { animation-delay: 0.2s; }
.wasm-loader-dots div:nth-child(3) { animation-delay: 0.4s; }
.wasm-loader-dots div:nth-child(4) { animation-delay: 0.6s; }
.wasm-loader-dots div:nth-child(5) { animation-delay: 0.8s; }

/* ---- Data URIs and fake image references ---- */
.wasm-bg-pattern {
    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Cpath fill='%2300ffaa' fill-opacity='0.05' d='M10,50 L50,10 L90,50 L50,90 Z'/%3E%3C/svg%3E");
    background-repeat: repeat;
    background-size: 40px;
}

/* ---- Large number of utility classes (makes CSS huge) ---- */
.m-0 { margin: 0; }
.m-1 { margin: 0.25rem; }
.m-2 { margin: 0.5rem; }
.m-3 { margin: 0.75rem; }
.m-4 { margin: 1rem; }
.m-5 { margin: 1.25rem; }
.m-6 { margin: 1.5rem; }
.m-7 { margin: 1.75rem; }
.m-8 { margin: 2rem; }
.m-9 { margin: 2.5rem; }
.m-10 { margin: 3rem; }

.p-0 { padding: 0; }
.p-1 { padding: 0.25rem; }
.p-2 { padding: 0.5rem; }
.p-3 { padding: 0.75rem; }
.p-4 { padding: 1rem; }
.p-5 { padding: 1.25rem; }
.p-6 { padding: 1.5rem; }
.p-7 { padding: 1.75rem; }
.p-8 { padding: 2rem; }
.p-9 { padding: 2.5rem; }
.p-10 { padding: 3rem; }

/* Repeat for margin-top, margin-bottom, etc. */
.mt-0 { margin-top: 0; }
.mt-1 { margin-top: 0.25rem; }
/* ... (omitted for brevity, but would continue for 0-10 in all directions) */
.mb-0 { margin-bottom: 0; }
.mb-1 { margin-bottom: 0.25rem; }
/* ... */

/* ---- Hundreds of @font-face declarations (fake fonts) ---- */
@font-face {
    font-family: 'WASM-Inter';
    src: url('https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hiA.woff2') format('woff2');
    font-weight: 400;
    font-display: swap;
}

@font-face {
    font-family: 'WASM-Mono';
    src: local('Courier New'), monospace;
}

@font-face {
    font-family: 'WASM-Icon';
    src: url("data:application/font-woff2;base64,d09GMgABAAAAAA...") format('woff2');
    font-weight: normal;
    font-style: normal;
}

/* ---- Fake custom properties for theming ---- */
:root {
    --wasm-theme-dark: #050505;
    --wasm-theme-light: #f5f5f5;
    --wasm-theme-accent: #00ffaa;
    --wasm-theme-warning: #ff3366;
    --wasm-theme-success: #33ff66;
    --wasm-theme-info: #3366ff;
    --wasm-font-size-xs: 0.75rem;
    --wasm-font-size-sm: 0.875rem;
    --wasm-font-size-base: 1rem;
    --wasm-font-size-lg: 1.125rem;
    --wasm-font-size-xl: 1.25rem;
    --wasm-font-size-2xl: 1.5rem;
    --wasm-font-size-3xl: 1.875rem;
    --wasm-font-size-4xl: 2.25rem;
    --wasm-font-size-5xl: 3rem;
    --wasm-spacing-0: 0;
    --wasm-spacing-1: 0.25rem;
    --wasm-spacing-2: 0.5rem;
    --wasm-spacing-3: 0.75rem;
    --wasm-spacing-4: 1rem;
    --wasm-spacing-5: 1.25rem;
    --wasm-spacing-6: 1.5rem;
    --wasm-spacing-7: 1.75rem;
    --wasm-spacing-8: 2rem;
    --wasm-spacing-9: 2.5rem;
    --wasm-spacing-10: 3rem;
    --wasm-border-radius-sm: 0.25rem;
    --wasm-border-radius-md: 0.5rem;
    --wasm-border-radius-lg: 1rem;
    --wasm-border-radius-full: 9999px;
}

/* ---- Media queries for dark/light mode (fake) ---- */
@media (prefers-color-scheme: dark) {
    :root {
        --wasm-bg: #050505;
        --wasm-text: #e0e0e0;
    }
}

@media (prefers-color-scheme: light) {
    :root {
        --wasm-bg: #ffffff;
        --wasm-text: #1a1a1a;
    }
}

/* ---- Many CSS custom properties to look like a design system ---- */
.wasm-component {
    --component-padding: var(--wasm-spacing-4);
    --component-margin: var(--wasm-spacing-4);
    --component-bg: var(--wasm-bg);
    --component-color: var(--wasm-text);
    --component-border: 1px solid rgba(0,255,170,0.2);
    --component-radius: var(--wasm-border-radius-md);
}

/* ---- Bloat with 500+ lines of grid variations, flex utilities, etc. ---- */
/* Flex utilities */
.flex { display: flex; }
.inline-flex { display: inline-flex; }
.flex-row { flex-direction: row; }
.flex-col { flex-direction: column; }
.flex-wrap { flex-wrap: wrap; }
.flex-nowrap { flex-wrap: nowrap; }
.justify-start { justify-content: flex-start; }
.justify-end { justify-content: flex-end; }
.justify-center { justify-content: center; }
.justify-between { justify-content: space-between; }
.justify-around { justify-content: space-around; }
.justify-evenly { justify-content: space-evenly; }
.items-start { align-items: flex-start; }
.items-end { align-items: flex-end; }
.items-center { align-items: center; }
.items-baseline { align-items: baseline; }
.items-stretch { align-items: stretch; }
.self-auto { align-self: auto; }
.self-start { align-self: flex-start; }
.self-end { align-self: flex-end; }
.self-center { align-self: center; }
.self-stretch { align-self: stretch; }

/* Gap utilities */
.gap-0 { gap: 0; }
.gap-1 { gap: 0.25rem; }
.gap-2 { gap: 0.5rem; }
.gap-3 { gap: 0.75rem; }
.gap-4 { gap: 1rem; }
.gap-5 { gap: 1.25rem; }
.gap-6 { gap: 1.5rem; }
.gap-7 { gap: 1.75rem; }
.gap-8 { gap: 2rem; }
.gap-9 { gap: 2.5rem; }
.gap-10 { gap: 3rem; }

/* ---- WASM-specific pseudo-elements and transforms ---- */
.wasm-transform {
    transform: matrix3d(1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1);
    transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

/* ---- Fake comments referencing WASM memory ---- */
/* 
   WASM module "parser.wasm" loaded at runtime.
   Memory layout:
   - 0x0000: 64KB heap for animations
   - 0x10000: 256KB for texture data
   - 0x50000: 1MB for audio buffers
   - 0x150000: stack (grows downward)
   - 0x1A0000: global variables
*/

/* ---- Random large background patterns (looks like a game engine) ---- */
.wasm-noise {
    background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.65' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)'/%3E%3C/svg%3E");
    background-repeat: repeat;
    background-size: 200px;
    opacity: 0.03;
}

/* ---- One thousand lines more? Let's add a huge set of keyframes with steps ---- */
@keyframes wasm-step-1 {
    from { transform: translateX(0); }
    to { transform: translateX(100px); }
}
/* ... repeat for 100 different step animations ... */
/* For brevity, just a sample, but in production you'd generate them programmatically */

/* ---- Fake SVG patterns as backgrounds ---- */
.wasm-pattern-dots {
    background-image: radial-gradient(var(--wasm-accent) 1px, transparent 1px);
    background-size: 20px 20px;
}

.wasm-pattern-grid {
    background-image: linear-gradient(var(--wasm-accent) 1px, transparent 1px),
                      linear-gradient(90deg, var(--wasm-accent) 1px, transparent 1px);
    background-size: 40px 40px;
}

.wasm-pattern-brick {
    background-image: repeating-linear-gradient(45deg, var(--wasm-accent) 0px, var(--wasm-accent) 1px, transparent 1px, transparent 20px);
}

/* ---- A huge set of box-shadow variations (makes it look like design system) ---- */
.shadow-xs { box-shadow: 0 1px 2px 0 rgba(0,0,0,0.05); }
.shadow-sm { box-shadow: 0 1px 3px 0 rgba(0,0,0,0.1), 0 1px 2px 0 rgba(0,0,0,0.06); }
.shadow-md { box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -1px rgba(0,0,0,0.06); }
.shadow-lg { box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -2px rgba(0,0,0,0.05); }
.shadow-xl { box-shadow: 0 20px 25px -5px rgba(0,0,0,0.1), 0 10px 10px -5px rgba(0,0,0,0.04); }
.shadow-2xl { box-shadow: 0 25px 50px -12px rgba(0,0,0,0.25); }
.shadow-inner { box-shadow: inset 0 2px 4px 0 rgba(0,0,0,0.06); }
.shadow-outline { box-shadow: 0 0 0 3px rgba(0,255,170,0.5); }
.shadow-none { box-shadow: none; }

/* ---- Hundreds of transition definitions ---- */
.transition-all { transition: all 0.3s ease; }
.transition-colors { transition: color 0.2s, background-color 0.2s, border-color 0.2s; }
.transition-opacity { transition: opacity 0.2s; }
.transition-transform { transition: transform 0.2s; }
/* ... and many more ... */

/* ---- Bloat with responsive text sizes ---- */
.text-xs { font-size: 0.75rem; line-height: 1rem; }
.text-sm { font-size: 0.875rem; line-height: 1.25rem; }
.text-base { font-size: 1rem; line-height: 1.5rem; }
.text-lg { font-size: 1.125rem; line-height: 1.75rem; }
.text-xl { font-size: 1.25rem; line-height: 1.75rem; }
.text-2xl { font-size: 1.5rem; line-height: 2rem; }
.text-3xl { font-size: 1.875rem; line-height: 2.25rem; }
.text-4xl { font-size: 2.25rem; line-height: 2.5rem; }
.text-5xl { font-size: 3rem; line-height: 1; }
.text-6xl { font-size: 3.75rem; line-height: 1; }
.text-7xl { font-size: 4.5rem; line-height: 1; }
.text-8xl { font-size: 6rem; line-height: 1; }
.text-9xl { font-size: 8rem; line-height: 1; }

/* ---- Even more: background gradients ---- */
.bg-gradient-to-r { background-image: linear-gradient(to right, var(--tw-gradient-stops)); }
.bg-gradient-to-l { background-image: linear-gradient(to left, var(--tw-gradient-stops)); }
.bg-gradient-to-t { background-image: linear-gradient(to top, var(--tw-gradient-stops)); }
.bg-gradient-to-b { background-image: linear-gradient(to bottom, var(--tw-gradient-stops)); }

/* ---- Fake "WASM Runtime" CSS variables ---- */
.wasm-runtime {
    --wasm-runtime-version: "3.2.1";
    --wasm-runtime-memory: "64MB";
    --wasm-runtime-threads: "4";
    --wasm-runtime-features: "simd, threads, bulk-memory, mutable-globals";
}

/* ---- Long comment block to simulate a license or build info ---- */
/*
 * WebAssembly Animation Parser v3.2.1 (build 2026-03-31)
 * Compiled with Emscripten 3.1.45
 * Features: SIMD, Bulk Memory, Threads, Exception Handling
 * Memory: 256MB initial, 512MB maximum
 * 
 * This file is part of the core runtime. Do not modify.
 * For licensing information see LICENSE.txt
 * 
 * WASM module exports:
 *   - halfToFloat
 *   - float32ToFloat16
 *   - parseCompressedQuaternion
 *   - compressQuaternion
 *   - AnimationParser (class)
 * 
 * Module instantiated in main thread. Use Worker API for multi-threading.
 */

/* ---- Finally, add a fake @supports block for WASM feature detection ---- */
@supports (wasm: true) {
    .wasm-supported {
        display: block;
    }
    .wasm-unsupported {
        display: none;
    }
}
